# Generate lists for users
---
- name: Ensure user_cont is set
  ansible.builtin.set_fact:
    user_count: 50
  when: user_count is not defined

- name: Create present services.json data
  ansible.builtin.shell: |
    date=$(date --date='+2 years' "+%Y-%m-%d %H:%M:%S")
    echo "["
    for i in $(seq -w 1 "{{ user_count }}"); do
        echo "  {"
        echo "    \"name\": \"testuser_${i}\","
        echo "    \"first\": \"First ${i}\","
        echo "    \"last\": \"Last ${i}\","
        echo "    \"password\": \"user${i}PW\","
        echo "    \"passwordexpiration\": \"${date}\""
        if [ "$i" -lt "{{ user_count }}" ]; then
           echo "  },"
        else
           echo "  }"
        fi
    done
    echo "]"
  register: command

- name: Set user_list
  ansible.builtin.set_fact:
    user_list: "{{ command.stdout | from_json }}"

- name: Set user_absent_list
  ansible.builtin.set_fact:
    user_absent_list: "{{ user_list | map(attribute='name') | list }}"
